[Config]
MinimumVersion=26

[Distribution]
Distribution=fedora
Release=rawhide
Snapshot=20260813.n.0
Mirror=https://kojipkgs.fedoraproject.org
Architecture=x86-64

[Output]
Format=disk
ImageId=axiom-host-h1
OutputDirectory=mkosi.output
ManifestFormat=json,changelog
Seed=4c4b8444-341f-5c3f-9620-5c0c7fb65223
CompressOutput=no

[Content]
Packages=kernel-core
         systemd
         systemd-udev
         systemd-boot
         device-mapper
         cryptsetup-libs
         util-linux-core
         dbus-broker
         nodejs24
         nodejs24-bin
         nodejs24-npm
         nodejs24-npm-bin
         git
         ca-certificates
WithDocs=no
Bootable=yes
Bootloader=systemd-boot
UnifiedKernelImages=unsigned
Ssh=never
Autologin=no
KernelCommandLine=console=ttyS0 rd.systemd.show_status=yes systemd.show_status=yes systemd.journald.forward_to_console=yes
RemoveFiles=/var/cache/ldconfig/aux-cache

[Validation]
Checksum=yes
Verity=hash

[Build]
ToolsTree=yes
ToolsTreeDistribution=fedora
ToolsTreeRelease=rawhide
ToolsTreeMirror=https://kojipkgs.fedoraproject.org
Environment=E2FSPROGS_FAKE_TIME SYSTEMD_REPART_MKFS_OPTIONS_VFAT
WithNetwork=no

[Runtime]
VirtualMachineMonitor=qemu
Firmware=uefi
TPM=no
RuntimeNetwork=none
Ephemeral=no
CPUs=2
RAM=3G
