[profile.default]
src = "grid/contracts/contracts"
test = "grid/contracts/test"
script = "grid/contracts/script"
out = "out"
libs = ["grid/contracts/lib", "grid/contracts/node_modules"]
remappings = [
  "@openzeppelin/=grid/contracts/node_modules/@openzeppelin/",
  "forge-std/=grid/contracts/lib/forge-std/src/"
]
