// Code generated by capnpc-go. DO NOT EDIT.

package types

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
)

type Modality uint16

// Modality_TypeID is the unique identifier for the type Modality.
const Modality_TypeID = 0x8cc18c2d060bfca1

// Values of Modality.
const (
	Modality_text         Modality = 0
	Modality_latentVector Modality = 1
	Modality_graphDelta   Modality = 2
	Modality_zkProof      Modality = 3
)

// String returns the enum's constant name.
func (c Modality) String() string {
	switch c {
	case Modality_text:
		return "text"
	case Modality_latentVector:
		return "latentVector"
	case Modality_graphDelta:
		return "graphDelta"
	case Modality_zkProof:
		return "zkProof"

	default:
		return ""
	}
}

// ModalityFromString returns the enum value with a name,
// or the zero value if there's no such value.
func ModalityFromString(c string) Modality {
	switch c {
	case "text":
		return Modality_text
	case "latentVector":
		return Modality_latentVector
	case "graphDelta":
		return Modality_graphDelta
	case "zkProof":
		return Modality_zkProof

	default:
		return 0
	}
}

type Modality_List = capnp.EnumList[Modality]

func NewModality_List(s *capnp.Segment, sz int32) (Modality_List, error) {
	return capnp.NewEnumList[Modality](s, sz)
}

type ProposalType uint16

// ProposalType_TypeID is the unique identifier for the type ProposalType.
const ProposalType_TypeID = 0xfa75bb66cc3c9210

// Values of ProposalType.
const (
	ProposalType_unspecified ProposalType = 0
	ProposalType_modelRun    ProposalType = 1
)

// String returns the enum's constant name.
func (c ProposalType) String() string {
	switch c {
	case ProposalType_unspecified:
		return "unspecified"
	case ProposalType_modelRun:
		return "modelRun"

	default:
		return ""
	}
}

// ProposalTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func ProposalTypeFromString(c string) ProposalType {
	switch c {
	case "unspecified":
		return ProposalType_unspecified
	case "modelRun":
		return ProposalType_modelRun

	default:
		return 0
	}
}

type ProposalType_List = capnp.EnumList[ProposalType]

func NewProposalType_List(s *capnp.Segment, sz int32) (ProposalType_List, error) {
	return capnp.NewEnumList[ProposalType](s, sz)
}

type ProposalTensor capnp.Struct

// ProposalTensor_TypeID is the unique identifier for the type ProposalTensor.
const ProposalTensor_TypeID = 0xb1c9669c4ad47480

func NewProposalTensor(s *capnp.Segment) (ProposalTensor, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return ProposalTensor(st), err
}

func NewRootProposalTensor(s *capnp.Segment) (ProposalTensor, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return ProposalTensor(st), err
}

func ReadRootProposalTensor(msg *capnp.Message) (ProposalTensor, error) {
	root, err := msg.Root()
	return ProposalTensor(root.Struct()), err
}

func (s ProposalTensor) String() string {
	str, _ := text.Marshal(0xb1c9669c4ad47480, capnp.Struct(s))
	return str
}

func (s ProposalTensor) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ProposalTensor) DecodeFromPtr(p capnp.Ptr) ProposalTensor {
	return ProposalTensor(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ProposalTensor) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ProposalTensor) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ProposalTensor) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ProposalTensor) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ProposalTensor) ProposalType() ProposalType {
	return ProposalType(capnp.Struct(s).Uint16(0))
}

func (s ProposalTensor) SetProposalType(v ProposalType) {
	capnp.Struct(s).SetUint16(0, uint16(v))
}

func (s ProposalTensor) TensorShape() (capnp.UInt32List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.UInt32List(p.List()), err
}

func (s ProposalTensor) HasTensorShape() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ProposalTensor) SetTensorShape(v capnp.UInt32List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewTensorShape sets the tensorShape field to a newly
// allocated capnp.UInt32List, preferring placement in s's segment.
func (s ProposalTensor) NewTensorShape(n int32) (capnp.UInt32List, error) {
	l, err := capnp.NewUInt32List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt32List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s ProposalTensor) TensorDtype() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ProposalTensor) HasTensorDtype() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ProposalTensor) TensorDtypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ProposalTensor) SetTensorDtype(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// ProposalTensor_List is a list of ProposalTensor.
type ProposalTensor_List = capnp.StructList[ProposalTensor]

// NewProposalTensor creates a new list of ProposalTensor.
func NewProposalTensor_List(s *capnp.Segment, sz int32) (ProposalTensor_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[ProposalTensor](l), err
}

// ProposalTensor_Future is a wrapper for a ProposalTensor promised by a client call.
type ProposalTensor_Future struct{ *capnp.Future }

func (f ProposalTensor_Future) Struct() (ProposalTensor, error) {
	p, err := f.Future.Ptr()
	return ProposalTensor(p.Struct()), err
}

type EpistemicState capnp.Struct

// EpistemicState_TypeID is the unique identifier for the type EpistemicState.
const EpistemicState_TypeID = 0xe5527bca53cef4e7

func NewEpistemicState(s *capnp.Segment) (EpistemicState, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return EpistemicState(st), err
}

func NewRootEpistemicState(s *capnp.Segment) (EpistemicState, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return EpistemicState(st), err
}

func ReadRootEpistemicState(msg *capnp.Message) (EpistemicState, error) {
	root, err := msg.Root()
	return EpistemicState(root.Struct()), err
}

func (s EpistemicState) String() string {
	str, _ := text.Marshal(0xe5527bca53cef4e7, capnp.Struct(s))
	return str
}

func (s EpistemicState) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EpistemicState) DecodeFromPtr(p capnp.Ptr) EpistemicState {
	return EpistemicState(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EpistemicState) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EpistemicState) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EpistemicState) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EpistemicState) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EpistemicState) EntropyLevel() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(0))
}

func (s EpistemicState) SetEntropyLevel(v float32) {
	capnp.Struct(s).SetUint32(0, math.Float32bits(v))
}

func (s EpistemicState) LyapunovDepth() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s EpistemicState) SetLyapunovDepth(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s EpistemicState) ThrashingFlag() bool {
	return capnp.Struct(s).Bit(64)
}

func (s EpistemicState) SetThrashingFlag(v bool) {
	capnp.Struct(s).SetBit(64, v)
}

// EpistemicState_List is a list of EpistemicState.
type EpistemicState_List = capnp.StructList[EpistemicState]

// NewEpistemicState creates a new list of EpistemicState.
func NewEpistemicState_List(s *capnp.Segment, sz int32) (EpistemicState_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[EpistemicState](l), err
}

// EpistemicState_Future is a wrapper for a EpistemicState promised by a client call.
type EpistemicState_Future struct{ *capnp.Future }

func (f EpistemicState_Future) Struct() (EpistemicState, error) {
	p, err := f.Future.Ptr()
	return EpistemicState(p.Struct()), err
}

type IntentPayload capnp.Struct

// IntentPayload_TypeID is the unique identifier for the type IntentPayload.
const IntentPayload_TypeID = 0x93bd772929e16853

func NewIntentPayload(s *capnp.Segment) (IntentPayload, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 6})
	return IntentPayload(st), err
}

func NewRootIntentPayload(s *capnp.Segment) (IntentPayload, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 6})
	return IntentPayload(st), err
}

func ReadRootIntentPayload(msg *capnp.Message) (IntentPayload, error) {
	root, err := msg.Root()
	return IntentPayload(root.Struct()), err
}

func (s IntentPayload) String() string {
	str, _ := text.Marshal(0x93bd772929e16853, capnp.Struct(s))
	return str
}

func (s IntentPayload) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IntentPayload) DecodeFromPtr(p capnp.Ptr) IntentPayload {
	return IntentPayload(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IntentPayload) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IntentPayload) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IntentPayload) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IntentPayload) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s IntentPayload) Id() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s IntentPayload) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s IntentPayload) SetId(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s IntentPayload) SenderPubKey() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s IntentPayload) HasSenderPubKey() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s IntentPayload) SetSenderPubKey(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

func (s IntentPayload) Timestamp() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s IntentPayload) SetTimestamp(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s IntentPayload) Modality() Modality {
	return Modality(capnp.Struct(s).Uint16(8))
}

func (s IntentPayload) SetModality(v Modality) {
	capnp.Struct(s).SetUint16(8, uint16(v))
}

func (s IntentPayload) Payload() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s IntentPayload) HasPayload() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s IntentPayload) SetPayload(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

func (s IntentPayload) ProposalTensor() (ProposalTensor, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return ProposalTensor(p.Struct()), err
}

func (s IntentPayload) HasProposalTensor() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s IntentPayload) SetProposalTensor(v ProposalTensor) error {
	return capnp.Struct(s).SetPtr(5, capnp.Struct(v).ToPtr())
}

// NewProposalTensor sets the proposalTensor field to a newly
// allocated ProposalTensor struct, preferring placement in s's segment.
func (s IntentPayload) NewProposalTensor() (ProposalTensor, error) {
	ss, err := NewProposalTensor(capnp.Struct(s).Segment())
	if err != nil {
		return ProposalTensor{}, err
	}
	err = capnp.Struct(s).SetPtr(5, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s IntentPayload) EpistemicState() (EpistemicState, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return EpistemicState(p.Struct()), err
}

func (s IntentPayload) HasEpistemicState() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s IntentPayload) SetEpistemicState(v EpistemicState) error {
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewEpistemicState sets the epistemicState field to a newly
// allocated EpistemicState struct, preferring placement in s's segment.
func (s IntentPayload) NewEpistemicState() (EpistemicState, error) {
	ss, err := NewEpistemicState(capnp.Struct(s).Segment())
	if err != nil {
		return EpistemicState{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s IntentPayload) Signature() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return []byte(p.Data()), err
}

func (s IntentPayload) HasSignature() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s IntentPayload) SetSignature(v []byte) error {
	return capnp.Struct(s).SetData(4, v)
}

// IntentPayload_List is a list of IntentPayload.
type IntentPayload_List = capnp.StructList[IntentPayload]

// NewIntentPayload creates a new list of IntentPayload.
func NewIntentPayload_List(s *capnp.Segment, sz int32) (IntentPayload_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 6}, sz)
	return capnp.StructList[IntentPayload](l), err
}

// IntentPayload_Future is a wrapper for a IntentPayload promised by a client call.
type IntentPayload_Future struct{ *capnp.Future }

func (f IntentPayload_Future) Struct() (IntentPayload, error) {
	p, err := f.Future.Ptr()
	return IntentPayload(p.Struct()), err
}
func (p IntentPayload_Future) ProposalTensor() ProposalTensor_Future {
	return ProposalTensor_Future{Future: p.Future.Field(5, nil)}
}
func (p IntentPayload_Future) EpistemicState() EpistemicState_Future {
	return EpistemicState_Future{Future: p.Future.Field(3, nil)}
}

const schema_d30d07ce540e009c = "x\xda|SO\x88\x1bU\x1c\xfe\xbe\xf7&I[7" +
	"M\x1e\xc9\xa5\x0be\x15\xbc\xacP\xff\xb0\x07\xa1\x08[" +
	"\x96\xad`\xecB\xdef\x15\xf5\xa2o\x93\xb7\xc9\xd4\xc9" +
	"\xcc0\xf3R\xcdz\xa8\x1e\xbc\xedI\xf1\xd6\x8b\x07\x0f" +
	"\x1eD<\x8a\xf4\xe0I\x94R\x10+xPP\xb0\xd8" +
	"\x8bP\xa1\x07\x95\xca\xc8K\xb6\x93jio/\xbf|" +
	"\xbf?\xdf\x9fy\xf2\x80g\x82\xa7\xea+\x12B?Z" +
	"\xa9\x16\x1f\xde~\xa8z\xea\xe0\xcb\x03\xa8e\xf1\xcf\xa5" +
	"\xe3;Wk\xf5\xef\xc0\xb5\x09\x97\xd9z\x975\xa0\xf5" +
	"\x0e\x87`\xd1\x1b\xfd\xb2\xba\xfa\xc6\xe5\xf7\xa1\x97Y\x02" +
	"+\xd5\x1a\xb0\xf6\x097\xd8\xba\xec\xb1k\x9f\xf3+\x82" +
	"\xc5\xdb\xeeZ\xe7\xd2\xde\xd7\x9fy0K\xb0\xf0\x88\x0f" +
	"d\x87\xad\x8f\xa5\x1f\xfc\x91\xfc\x14,~\xbbu\xb5\xf7" +
	"\xcd[\xdb\xd7\xff38\xf0\xd0\x97\x83\x0e[c\xffl" +
	"\x85\x81\x876\xdf{\xe6\xca\xde\x17\x93\xbf\xffwk\xbd" +
	"r\x9a\xad\x93\x15\x8f;Qy\x1a\xa7\x8a\xbc?\xb2c" +
	"\x93?!M\xd8O_\x0dcgc\xf7x\xdf\xa4q" +
	"zz+\x19\x98(\x94n\xda%u\x93\x02P\xab\x8f" +
	"\x01\xa4z\xe4<@\xa1N\xbe\x02P\xaa\x13\x1b@\xc3" +
	"\xd97]\x11\x19\xdf\xfe\xa2E\xa3\xef\x92\xac\x18f&" +
	"\x1dm\xda\x08\xd2\x99\x8b\xfb\xafw\xb3$\xd9+\x17\x06" +
	"\xf7.|n\xf6\xa3k\xa6Qb\x06\xf0[\x1f\x96\x01" +
	"\x10\x10P\xdf.\x03\xfa\x8a\xa4\xfeAP\x91m\xfa\xe2" +
	"\xf7\xe7\x01}MR\xff,H\xd1\x9e\x9d\xf8\xd36\xa0" +
	"\x7f\x94\xd47\x04\x95\x0c\xda\x94\x80\xba\xde\x01\xf4\xaf\x92" +
	"\xfa\xa6\xa0\x0aD\x9b\x01\xa0~\xdf\x00\xf4\x0dI}K" +
	"PUe\x9b\x15@\xfd\xb1\x0f\xe8\x9b\x92\xfa\xb6\xa0\xaa" +
	"\x05mV\x01\xf5\x97\x9f\xf9\xa7d/\xa0\xa0\xaaT\xda" +
	"3\xb3\xc9}`\x9b\x92\xbd%\x0a\xcap\xc0:\x04\xeb" +
	"`\x91\xdbx`\xb3\xee\x04\x8d\xdd\xe7\xed\xb4,\xbbp" +
	"lsg\xc6`\xca\xa3\x10<\x0a\x16\xe3\x99\xc8n\x0a" +
	"\x80\x8dE\xc2@6\xc0\x8b\xe9\\\x8br\x82M\xc3\xdc" +
	"\xd9q\x88\xf5~\xcf\x19g\xd9\\d\x02d\xd3\xef\x0e" +
	"\x87\xb1q\x93\x0c\xb4e[\x9a%i\x92\x9b\x08\xeb;" +
	"6\xce\x93\x8c\xcdE\xec\xee\xb4\xdd\xdf\x96\xeea\xf7\xbc" +
	"\x173c\x96Jc\xcez\x0f6%uW\xf0\x8e/" +
	"[\xbb\x80>'\xa9G\x82Jpn\x8c\xf5\xc5\x81\xa4" +
	"N\xc5]\x175v\xa6\xa9ec\x91\xd79\xf3\xc2\xcd" +
	"\x96\xf5F\xa8\x99\xd4\xf28\xd8\x95\xe4\x11\x08\xff<\xfc" +
	"s\xd3\xa1\xe6\x9b\x97 \xb8\xf4`\x0ag\x0fu\x9b\xab" +
	"\xf6 \x0ae\xb6\xb6\xb2C\x0e/y\x0eg\xe6\x1c^" +
	"\xf0\xc5\x1dI\xfd\x9a`ac\x97%\xe9\xf4\x1c\x1a\xf6" +
	"\x82\x8dx\x0c\x82\xc7\xc0\"\x9a\x9at\x12'\x17\xb0\xb2" +
	"iS7*\xebn\x94\x99|\x14\xc6X\x19>\x1b\x99" +
	"!\x09A\xdeu\xb6\xbc\x9f\xf2\xeb&\xf2\"\xf9\x9b\x8f" +
	"\xcc\xaeP\xbb\xb3\xaf\xb0\xde\x01\x8aI\x9c\xa7\xb6\x1f\xee" +
	"\xa1\x16\xda\x81O\x93\x8d\xb6'1\x80\x7f\x03\x00\x00\xff" +
	"\xff\xd1';m"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_d30d07ce540e009c,
		Nodes: []uint64{
			0x8cc18c2d060bfca1,
			0x93bd772929e16853,
			0xb1c9669c4ad47480,
			0xe5527bca53cef4e7,
			0xfa75bb66cc3c9210,
		},
		Compressed: true,
	})
}
