import assert from 'node:assert/strict';
import test from 'node:test';
import { DELEGATED_GATE_MANDATE_SCHEMA, evaluateDelegatedGateMandate, validateDelegatedGateMandate } from '../src/domain/delegated-gate-mandate.mjs';
function mandate(){return {schema:DELEGATED_GATE_MANDATE_SCHEMA,mandate_id:'mandate:1',grantor:'principal:human',delegate:'agent:personal',domains:['health'],actions:['disclosure.projection'],purposes:['routine-care'],data_classes:['restricted'],destinations:['institution:clinic'],resource_ceilings:{max_records:1,max_value_minor:0},assurance_ceiling:'high-assurance',allowed_gate_decisions:['minimum-disclosure','credential-refresh'],escalation_conditions:['novel-purpose','new-destination','insufficient-evidence'],credential_rules:{allow_opaque_handle:true,allow_raw_secret:false},retention_constraints:['no-new-retention'],starts_at:'2026-09-03T00:00:00.000Z',expires_at:'2026-09-04T00:00:00.000Z',revocation:{revoked:false,revoked_at:null,reason:null},delegation:{mode:'none'},receipt_required:true};}
const req={delegate:'agent:personal',domain:'health',action:'disclosure.projection',purpose:'routine-care',data_class:'restricted',destination:'institution:clinic',assurance_profile:'enhanced',gate_decision:'minimum-disclosure',resource_usage:{records:1,value_minor:0}};

test('delegated agent can clear an in-scope gate without minting effect authority',()=>{const result=evaluateDelegatedGateMandate(mandate(),req,{now:'2026-09-03T12:00:00.000Z'});assert.deepEqual(result,{gate_authorized:true,reason_code:'mandate_scope_satisfied'});assert.equal(Object.hasOwn(result,'execution_authority'),false);});

test('expired, revoked, and scope-widening requests do not clear gates',()=>{assert.equal(evaluateDelegatedGateMandate(mandate(),req,{now:'2026-09-05T00:00:00.000Z'}).reason_code,'mandate_expired');const revoked=mandate();revoked.revocation={revoked:true,revoked_at:'2026-09-03T10:00:00.000Z',reason:'owner-revoked'};assert.equal(evaluateDelegatedGateMandate(revoked,req,{now:'2026-09-03T12:00:00.000Z'}).reason_code,'mandate_revoked');assert.equal(evaluateDelegatedGateMandate(mandate(),{...req,purpose:'research'},{now:'2026-09-03T12:00:00.000Z'}).reason_code,'purpose_out_of_scope');});

test('resource ceilings are enforced before a delegated gate may clear',()=>{assert.equal(evaluateDelegatedGateMandate(mandate(),{...req,resource_usage:{records:2,value_minor:0}},{now:'2026-09-03T12:00:00.000Z'}).reason_code,'resource_records_exceeds_ceiling');assert.equal(evaluateDelegatedGateMandate(mandate(),{...req,resource_usage:{records:1,value_minor:1}},{now:'2026-09-03T12:00:00.000Z'}).reason_code,'resource_value_exceeds_ceiling');});

test('delegated gate requests reject inferred preferences and undeclared request fields',()=>{assert.throws(()=>evaluateDelegatedGateMandate(mandate(),{...req,learned_preference:'always approve'},{now:'2026-09-03T12:00:00.000Z'}),/unknown field learned_preference/);});

test('mandate schema rejects execution grants and unrestricted delegation',()=>{assert.throws(()=>validateDelegatedGateMandate({...mandate(),execution_authority:['health.read']}),/execution authority/);const widened=mandate();widened.delegation={mode:'unrestricted'};assert.throws(()=>validateDelegatedGateMandate(widened),/delegation/);});
