import assert from 'node:assert/strict';
import test from 'node:test';
import { entityFoundationDigest } from '../src/lib/entity-foundation.mjs';
import { entityLayerDigest } from '../src/lib/entity-layer.mjs';
import { supersedeEntityLayer } from '../src/lib/entity-layer-transitions.mjs';

function foundation(){return {schema:'axiom-entity-foundation.v0',version:0,status:'inert-contract-laboratory',foundation_id:'foundation.evolution',entity_id:'entity.evolution',lineage_root_id:'lineage.evolution',profile:'blank-egg',core_contract_refs:['contract.agency.v0'],recovery_policy_ref:null,privacy_policy_ref:null,personal_grounding_present:false,worldview_layers_present:false,disposition_layers_present:false,provider_binding_present:false,created_at:'2026-09-01T12:00:00.000Z',authority_effect:'none',network_effect:'none',runtime_activation:false};}
function layerV1(){return {schema:'axiom-entity-layer.v0',version:0,status:'inert-contract-laboratory',layer_id:'layer.judgment.v1',layer_version:1,layer_class:'judgment',artifact_ref:'artifact.judgment.v1',artifact_digest:'a'.repeat(64),authors:['principal.initial-author'],adopter_principal_id:'entity.evolution',endorsement_mode:'entity',provenance_refs:['provenance.judgment.v1'],influence_scopes:['judgment-heuristic'],privacy_class:'public',mutability:'evolvable',dependencies:[],conflicts:[],predecessor_layer_ref:null,created_at:'2026-09-01T12:00:00.000Z',adopted_at:'2026-09-01T12:01:00.000Z',expires_at:null,contains_raw_private_content:false,authority_effect:'none',network_effect:'none',runtime_activation:false};}
function successor(){return {schema:'axiom-entity-layer.v0',version:0,status:'inert-contract-laboratory',layer_id:'layer.self-authored.v2',layer_version:2,layer_class:'self-authored',artifact_ref:'artifact.self-authored.v2',artifact_digest:'b'.repeat(64),authors:['entity.evolution'],adopter_principal_id:'entity.evolution',endorsement_mode:'entity',provenance_refs:['decision.evolution.v2'],influence_scopes:['judgment-heuristic'],privacy_class:'public',mutability:'evolvable',dependencies:[],conflicts:[],predecessor_layer_ref:'layer.judgment.v1',created_at:'2026-09-01T12:02:00.000Z',adopted_at:'2026-09-01T12:03:00.000Z',expires_at:null,contains_raw_private_content:false,authority_effect:'none',network_effect:'none',runtime_activation:false};}
function stack(f,l){return {schema:'axiom-entity-layer-stack.v0',version:0,status:'inert-contract-laboratory',stack_id:'stack.evolution',foundation_id:f.foundation_id,foundation_digest:entityFoundationDigest(f),active_layers:[{layer_id:l.layer_id,layer_digest:entityLayerDigest(l),precedence:10}],suspended_layer_ids:[],superseded_layer_ids:[],created_at:'2026-09-01T12:01:00.000Z',updated_at:'2026-09-01T12:01:00.000Z',authority_effect:'none',network_effect:'none',runtime_activation:false};}

test('self-authored successor replaces active influence while preserving predecessor history',()=>{const f=foundation(),current=layerV1(),next=successor(),s=stack(f,current);const result=supersedeEntityLayer(s,current,next,{updated_at:'2026-09-01T12:04:00.000Z'});assert.deepEqual(result.active_layers,[{layer_id:next.layer_id,layer_digest:entityLayerDigest(next),precedence:10}]);assert.deepEqual(result.superseded_layer_ids,[current.layer_id]);assert.equal(result.foundation_id,s.foundation_id);assert.equal(result.foundation_digest,s.foundation_digest);assert.equal(result.authority_effect,'none');assert.equal(result.network_effect,'none');assert.equal(result.runtime_activation,false);});

test('successor must explicitly cite the active predecessor and advance version',()=>{const f=foundation(),current=layerV1(),s=stack(f,current);assert.throws(()=>supersedeEntityLayer(s,current,{...successor(),predecessor_layer_ref:null},{updated_at:'2026-09-01T12:04:00.000Z'}),/predecessor/i);assert.throws(()=>supersedeEntityLayer(s,current,{...successor(),layer_version:1},{updated_at:'2026-09-01T12:04:00.000Z'}),/layer_version/i);});

test('cannot supersede a layer that is not exactly active in the stack',()=>{const f=foundation(),current=layerV1(),next=successor(),s=stack(f,current);assert.throws(()=>supersedeEntityLayer(s,{...current,artifact_digest:'f'.repeat(64)},next,{updated_at:'2026-09-01T12:04:00.000Z'}),/active predecessor digest/i);});
