import assert from 'node:assert/strict';
import test from 'node:test';
import { evaluateAssuranceProfile } from '../src/domain/assurance-profile.mjs';
import { buildEvidenceContext, validateEvidenceReviewState } from '../src/domain/evidence-graph.mjs';
import { evaluateDelegatedGateMandate } from '../src/domain/delegated-gate-mandate.mjs';
import { INFORMATION_RIGHTS_SCHEMA, validateInformationRightsEnvelope } from '../src/domain/information-rights.mjs';
import { CONTEXTUAL_DISCLOSURE_REQUEST_SCHEMA, selectMinimumSufficientProjection, validateContextualDisclosureRequest } from '../src/domain/contextual-disclosure.mjs';

const criticalConsequence={data_sensitivity:'highly-restricted',disclosure_breadth:'broad',third_party_impact:'material',monetary_exposure:'none',physical_safety_impact:'none',legal_regulatory_consequence:'material',clinical_consequence:'severe',employment_eligibility_consequence:'none',governance_authority_consequence:'none',trust_root_impact:'none',reversibility:'irreversible',affected_population:'one',destination_currentness:'current',evidence_freshness:'current',runtime_uncertainty:'low',contestability:'disputed'};
const delegatedMandate={schema:'axiom-delegated-gate-mandate.v1',mandate_id:'mandate:invariant',grantor:'principal:human',delegate:'agent:personal',domains:['health'],actions:['disclosure.projection'],purposes:['routine-care'],data_classes:['restricted'],destinations:['institution:clinic'],resource_ceilings:{max_records:1,max_value_minor:0},assurance_ceiling:'high-assurance',allowed_gate_decisions:['minimum-disclosure'],escalation_conditions:['novel-purpose'],credential_rules:{allow_opaque_handle:true,allow_raw_secret:false},retention_constraints:['no-new-retention'],starts_at:'2026-09-03T00:00:00.000Z',expires_at:'2026-09-04T00:00:00.000Z',revocation:{revoked:false,revoked_at:null,reason:null},delegation:{mode:'none'},receipt_required:true};
const delegatedRequest={delegate:'agent:personal',domain:'health',action:'disclosure.projection',purpose:'routine-care',data_class:'restricted',destination:'institution:clinic',assurance_profile:'enhanced',gate_decision:'minimum-disclosure'};
const at='2026-09-03T12:00:00.000Z';
const evidenceAssertions=[{schema:'axiom-evidence-assertion.v1',assertion_id:'assertion:h',type:'hypothesis',proposition:'Hypothesis A',source_ref:'principal:reviewer',epistemic_state:'asserted',purpose_scope:['investigation'],provenance_refs:['artifact:1'],created_at:at},{schema:'axiom-evidence-assertion.v1',assertion_id:'assertion:c',type:'counterevidence',proposition:'Evidence conflicts with A',source_ref:'principal:reviewer',epistemic_state:'asserted',purpose_scope:['investigation'],provenance_refs:['artifact:2'],created_at:at},{schema:'axiom-evidence-assertion.v1',assertion_id:'assertion:q',type:'challenge',proposition:'A is disputed',source_ref:'principal:reviewer',epistemic_state:'disputed',purpose_scope:['investigation'],provenance_refs:['artifact:3'],created_at:at}];
const evidenceLinks=[{schema:'axiom-evidence-link.v1',link_id:'link:c',from_ref:'assertion:c',to_ref:'assertion:h',relation:'contradicts',asserted_by:'principal:reviewer',created_at:at},{schema:'axiom-evidence-link.v1',link_id:'link:q',from_ref:'assertion:q',to_ref:'assertion:h',relation:'challenged-by',asserted_by:'principal:reviewer',created_at:at}];

test('high consequence changes assurance but never itself decides allow or deny',()=>{const result=evaluateAssuranceProfile(criticalConsequence);assert.equal(result.profile,'critical-assurance');for(const forbidden of ['allow','deny','authorized','execution_authority','requires_human_confirmation'])assert.equal(Object.hasOwn(result,forbidden),false);});
test('delegated gate clearance remains distinct from execution authority',()=>{const result=evaluateDelegatedGateMandate(delegatedMandate,delegatedRequest,{now:at});assert.equal(result.gate_authorized,true);assert.equal(Object.hasOwn(result,'execution_authority'),false);assert.equal(Object.hasOwn(result,'capability_grant'),false);});
test('evidence context cannot collapse to the dominant narrative',()=>{const context=buildEvidenceContext({assertions:evidenceAssertions,links:evidenceLinks,focus_ids:['assertion:h']});assert.ok(context.links.some(link=>link.relation==='contradicts'));assert.ok(context.links.some(link=>link.relation==='challenged-by'));});

function rights(subjects,originators){return {schema:INFORMATION_RIGHTS_SCHEMA,object_ref:'record:test',information_class:'note',sensitivity_class:'restricted',relationships:{subjects,originators,custodians:['institution:holder'],controllers:['institution:holder'],affected_parties:[],beneficiaries:[],permitted_recipients:[],reviewers:[],auditors:[],decision_users:[],challengers:[],disclosure_authorities:['policy:access'],retention_authorities:['policy:retain']},authority_basis:['policy:access'],allowed_purposes:['care'],forbidden_purposes:[],policy_refs:{access:['policy:access'],disclosure:['policy:disclosure'],retention:['policy:retain'],challenge:[],correction:[],export:[],deletion:[]},projection_profiles:[],jurisdiction_context:[],provenance_refs:[],evidence_refs:[],state:{retention:'active',challenge:'none',supersession:'current'},created_at:at,reviewed_at:null};}
test('subject relationship does not produce inspect-full-content authority',()=>{const value=validateInformationRightsEnvelope(rights(['principal:subject'],[]));assert.equal(Object.hasOwn(value,'inspect-full-content'),false);assert.equal(Object.hasOwn(value,'execution_authority'),false);});
test('originator relationship does not produce withhold-from-subject authority',()=>{const value=validateInformationRightsEnvelope(rights([],['principal:originator']));assert.equal(Object.hasOwn(value,'withhold-from-subject'),false);assert.equal(Object.hasOwn(value,'execution_authority'),false);});
test('availability, machine review, human review, and adjudication remain distinct',()=>{const value=validateEvidenceReviewState({schema:'axiom-evidence-review-state.v1',object_ref:'artifact:review',known:true,available:true,acquired:true,integrity_verified:true,indexed:true,machine_reviewed:true,human_reviewed:false,relied_upon:false,disclosed:false,challenged:false,adjudicated:false,updated_at:at});assert.equal(value.available,true);assert.equal(value.machine_reviewed,true);assert.equal(value.human_reviewed,false);assert.equal(value.adjudicated,false);});
test('contextual reputation-like claim projection does not return authority',()=>{const req={schema:CONTEXTUAL_DISCLOSURE_REQUEST_SCHEMA,request_id:'disclosure-request:reputation',requester:'institution:reviewer',subject_ref:'agent:worker',purpose:'reputation-check',required_claims:['experienced-reviewer'],requested_fields:[],verifier_policy_ref:'policy:review',created_at:at};const result=selectMinimumSufficientProjection({request:req,available_claims:[{claim_id:'claim:experience',predicate:'experienced-reviewer',value:true,evidence_refs:['evidence:history'],derived_from_fields:['review_count']}],available_fields:{review_count:42},policy:{allowed_claims:['experienced-reviewer'],allowed_raw_fields:[],required_authority_ref:'policy:projection'}});assert.equal(result.status,'satisfied');for(const forbidden of ['authorized','execution_authority','capability_grant'])assert.equal(Object.hasOwn(result,forbidden),false);});
test('learned preference cannot expand disclosure authority',()=>{const req={schema:CONTEXTUAL_DISCLOSURE_REQUEST_SCHEMA,request_id:'disclosure-request:pref',requester:'institution:clinic',subject_ref:'principal:user',purpose:'care',required_claims:[],requested_fields:[],verifier_policy_ref:'policy:care',created_at:at,learned_preference:'always approve'};assert.throws(()=>validateContextualDisclosureRequest(req),/unknown field learned_preference/);});
