"""
Spatial Web Parser for Carbonyl Terminal Browser Integration

Ingests terminal buffers generated by the Carbonyl browser.
Strips raw ANSI color codes but maintains the 2D spatial geometry of the text.
Provides the LLM with a 'visual' understanding of a webpage using pure, low-entropy text tokens.

Part of AxiomMesh's Terminal-Native Spatial Browsing system.
Replaces high-entropy pixel VLMs and bloated HTML DOM parsing with Spatial Text Matrices.
"""

import re
import logging
from typing import List, Tuple, Optional

logger = logging.getLogger("AxiomMesh-SpatialWeb")


class SpatialWebParser:
    """
    Converts Carbonyl terminal output into a Geometric Context Matrix.
    
    The parser maintains the spatial layout of web elements as rendered in the terminal,
    allowing the 1.58-bit Ternary Engine to "see" UI layouts using standard text tokens
    with zero pixel-processing overhead.
    """
    
    def __init__(self, viewport_width: int = 120, viewport_height: int = 40):
        """
        Initialize the Spatial Web Parser with viewport dimensions.
        
        Args:
            viewport_width: Width of the terminal viewport in characters (default: 120)
            viewport_height: Height of the terminal viewport in lines (default: 40)
        """
        self.width = viewport_width
        self.height = viewport_height
        # Comprehensive ANSI escape sequence regex - strips colors, styles, cursor moves
        self.ansi_escape = re.compile(
            r'(?:\x1B[@-_]|[\x80-\x9F])[0-?]*[ -/]*[@-~]'
        )
        # Also match SGR color codes specifically
        self.sgr_codes = re.compile(r'\x1b\[[0-9;]*m')
        
    def strip_ansi(self, text: str) -> str:
        """
        Strip all ANSI escape sequences from text while preserving spatial layout.
        
        Args:
            text: Raw terminal buffer with ANSI codes
            
        Returns:
            Clean text with ANSI codes removed
        """
        clean = self.ansi_escape.sub('', text)
        clean = self.sgr_codes.sub('', clean)
        return clean
    
    def parse_carbonyl_buffer(self, raw_buffer: str) -> str:
        """
        Converts the Carbonyl terminal output into a Geometric Context Matrix.
        
        Args:
            raw_buffer: Raw ANSI-encoded terminal buffer from Carbonyl
            
        Returns:
            Formatted spatial matrix string for LLM consumption
        """
        # 1. Strip all color and style ANSI codes, keeping only physical layout spaces
        clean_text = self.strip_ansi(raw_buffer)
        
        # 2. Reconstruct the 2D grid
        lines = clean_text.split('\n')
        matrix_view = ["[SPATIAL WEB MATRIX START]"]
        
        # Add coordinate rulers for the LLM to target clicks
        ruler = "    " + "".join([str(i % 10) for i in range(self.width)])
        matrix_view.append(ruler)
        matrix_view.append("    " + "-" * self.width)
        
        for y, line in enumerate(lines[:self.height]):
            # Remove any trailing whitespace that might interfere with grid math
            line = line.rstrip('\r')
            # Pad or truncate to exact viewport width to maintain strict grid math
            normalized_line = line.ljust(self.width)[:self.width]
            # Prefix with Y-coordinate
            matrix_view.append(f"{y:03d}|{normalized_line}|")
            
        matrix_view.append("[SPATIAL WEB MATRIX END]")
        matrix_view.append("")
        matrix_view.append("DIRECTIVE: To interact, reply with X,Y coordinates based on the grid above.")
        matrix_view.append("FORMAT: CLICK:X,Y or NAVIGATE:direction or INPUT:X,Y:text")
        
        logger.debug(f"[🕸️] Compressed website into {self.width}x{self.height} Spatial Matrix.")
        return "\n".join(matrix_view)
    
    def extract_clickable_elements(self, raw_buffer: str) -> List[Tuple[int, int, str]]:
        """
        Identify clickable elements (buttons, links) in the spatial matrix.
        
        Args:
            raw_buffer: Raw ANSI-encoded terminal buffer from Carbonyl
            
        Returns:
            List of tuples: (x, y, element_description)
        """
        clean_text = self.strip_ansi(raw_buffer)
        lines = clean_text.split('\n')
        elements = []
        
        # Common patterns for interactive elements in terminal rendering
        button_patterns = [
            r'\[([^\]]+)\]',      # [Button Text]
            r'<([^\>]+)>',       # <Link Text>
            r'\(([^)]+)\)',      # (Action)
            r'🔗\s*(.+)',        # 🔗 Link
            r'🔘\s*(.+)',        # 🔘 Button
            r'➡️?\s*(.+)',       # → Arrow indicators
        ]
        
        for y, line in enumerate(lines[:self.height]):
            line = line.rstrip('\r')
            for pattern in button_patterns:
                for match in re.finditer(pattern, line):
                    x = match.start()
                    element_text = match.group(0).strip()
                    if element_text and len(element_text) > 1:
                        elements.append((x, y, element_text))
                        
        return elements
    
    def get_element_at_coordinate(self, raw_buffer: str, x: int, y: int) -> Optional[str]:
        """
        Get the element at a specific coordinate in the spatial matrix.
        
        Args:
            raw_buffer: Raw ANSI-encoded terminal buffer from Carbonyl
            x: X coordinate (column)
            y: Y coordinate (row)
            
        Returns:
            Character or element description at the coordinate, or None
        """
        clean_text = self.strip_ansi(raw_buffer)
        lines = clean_text.split('\n')
        
        if y >= len(lines) or y < 0:
            return None
            
        line = lines[y].rstrip('\r')
        if x >= len(line) or x < 0:
            return None
            
        return line[x]
    
    def generate_interaction_prompt(self, raw_buffer: str, task: str) -> str:
        """
        Generate an interaction prompt for the LLM with spatial context.
        
        Args:
            raw_buffer: Raw ANSI-encoded terminal buffer from Carbonyl
            task: The task the agent needs to perform
            
        Returns:
            Formatted prompt with spatial matrix and task instructions
        """
        matrix = self.parse_carbonyl_buffer(raw_buffer)
        elements = self.extract_clickable_elements(raw_buffer)
        
        prompt = f"""
{matrix}

=== TASK ===
{task}

=== DETECTED INTERACTIVE ELEMENTS ===
"""
        if elements:
            for x, y, desc in elements:
                prompt += f"  [{x:03d},{y:03d}] {desc}\n"
        else:
            prompt += "  No interactive elements detected.\n"
            
        prompt += """
=== INSTRUCTIONS ===
Respond with one of the following actions:
  - CLICK:X,Y     : Click on element at coordinates X,Y
  - TYPE:X,Y,text : Type text at input field at coordinates X,Y  
  - SCROLL:UP/DOWN: Scroll the page up or down
  - WAIT          : Wait for page to load/update
  - EXTRACT       : Extract relevant information from current view

Example: CLICK:025,012
"""
        return prompt


class CarbonylBufferStreamer:
    """
    Streams and buffers Carbonyl terminal output for real-time parsing.
    
    Maintains a rolling buffer of terminal frames for temporal analysis
    and change detection.
    """
    
    def __init__(self, max_frames: int = 10, viewport_width: int = 120, viewport_height: int = 40):
        """
        Initialize the buffer streamer.
        
        Args:
            max_frames: Maximum number of frames to keep in rolling buffer
            viewport_width: Width of terminal viewport
            viewport_height: Height of terminal viewport
        """
        self.max_frames = max_frames
        self.parser = SpatialWebParser(viewport_width, viewport_height)
        self.frames: List[str] = []
        self.timestamps: List[float] = []
        
    def add_frame(self, raw_buffer: str, timestamp: Optional[float] = None):
        """
        Add a new frame to the rolling buffer.
        
        Args:
            raw_buffer: Raw ANSI-encoded terminal buffer
            timestamp: Optional timestamp (defaults to current time)
        """
        import time
        if timestamp is None:
            timestamp = time.time()
            
        self.frames.append(raw_buffer)
        self.timestamps.append(timestamp)
        
        # Maintain rolling buffer size
        if len(self.frames) > self.max_frames:
            self.frames.pop(0)
            self.timestamps.pop(0)
            
    def detect_changes(self) -> bool:
        """
        Detect if the terminal content has changed between frames.
        
        Returns:
            True if changes detected, False otherwise
        """
        if len(self.frames) < 2:
            return False
            
        prev_clean = self.parser.strip_ansi(self.frames[-2])
        curr_clean = self.parser.strip_ansi(self.frames[-1])
        
        return prev_clean != curr_clean
    
    def get_latest_matrix(self) -> str:
        """
        Get the latest frame as a spatial matrix.
        
        Returns:
            Formatted spatial matrix string
        """
        if not self.frames:
            return "[SPATIAL WEB MATRIX START]\n[NO FRAMES AVAILABLE]\n[SPATIAL WEB MATRIX END]"
            
        return self.parser.parse_carbonyl_buffer(self.frames[-1])
