import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { meshConfig, MESH_ROOT } from './lib/config.mjs';
import { validateCapabilityRegistry } from './check-registry.mjs';

export const GOVERNING_CLAIM_DOCUMENTS = Object.freeze([
  'README.md',
  'CONSTITUTION.md',
  'docs/rebuild/PRODUCT-DEFINITION.md',
  'docs/rebuild/REQUIREMENTS.md'
]);

export function renderCapabilityStatus(registry) {
  const validation = validateCapabilityRegistry(registry);
  const counts = Object.entries(validation.counts)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([status, count]) => `- ${status}: ${count}`)
    .join('\n');
  const rows = registry.capabilities.map(item => (
    `| \`${item.id}\` | ${item.family} | **${item.status}** | ${escapeCell(item.summary)} |`
  )).join('\n');
  return `<!-- Generated by mesh/src/status.mjs. Do not edit manually. -->
# AXIOM-MESH Capability Status

Registry schema: \`${validation.schema}\`
Kernel version: \`${registry.kernel_version}\`
Evidence verified: \`${registry.verified_at}\`
Registry digest: \`${validation.digest}\`

Only **implemented** capabilities are runnable claims.

## Counts

${counts}

## Registry

| Capability | Family | Status | Verified claim or boundary |
|---|---|---|---|
${rows}
`;
}

export function renderRegistryMarker(registry) {
  const validation = validateCapabilityRegistry(registry);
  return `<!-- axiom-capability-registry: schema=${validation.schema}; kernel=${registry.kernel_version}; digest=${validation.digest} -->`;
}

async function main() {
  const config = meshConfig();
  const registry = JSON.parse(await readFile(config.capabilitiesPath, 'utf8'));
  const rendered = renderCapabilityStatus(registry);
  const repositoryRoot = dirname(MESH_ROOT);
  const outputPath = join(repositoryRoot, 'docs', 'rebuild', 'STATUS.md');
  if (process.argv.includes('--write')) {
    await writeFile(outputPath, rendered);
    await synchronizeRegistryMarkers(repositoryRoot, registry);
    process.stdout.write(`${outputPath}\n`);
    return;
  }
  const existing = await readFile(outputPath, 'utf8');
  if (existing !== rendered) throw new Error('docs/rebuild/STATUS.md is stale; run npm run status:generate');
  await verifyRegistryMarkers(repositoryRoot, registry);
  process.stdout.write(`${JSON.stringify({ valid: true, path: outputPath })}\n`);
}

export async function verifyRegistryMarkers(repositoryRoot, registry) {
  const expected = renderRegistryMarker(registry);
  for (const relativePath of GOVERNING_CLAIM_DOCUMENTS) {
    const content = await readFile(join(repositoryRoot, relativePath), 'utf8');
    if (!content.includes(expected)) {
      throw new Error(`${relativePath} has stale capability-registry metadata; run npm run status:generate`);
    }
  }
}

async function synchronizeRegistryMarkers(repositoryRoot, registry) {
  const marker = renderRegistryMarker(registry);
  for (const relativePath of GOVERNING_CLAIM_DOCUMENTS) {
    const path = join(repositoryRoot, relativePath);
    const content = await readFile(path, 'utf8');
    const next = content.match(/^<!-- axiom-capability-registry: [^\n]+ -->\n/)
      ? content.replace(/^<!-- axiom-capability-registry: [^\n]+ -->/, marker)
      : `${marker}\n${content}`;
    await writeFile(path, next);
  }
}

function escapeCell(value) {
  return String(value).replaceAll('|', '\\|').replaceAll('\n', ' ');
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
